from MDAnalysis import *
import numpy
from string import split

system =  AtomGroup.Universe("../../pca/ca.psf" , "../../pca/130_55.dcd")
salt1 = system.selectAtoms(" ( ( resid 33 or resid 156 ) and name CA ) ")
salt2 = system.selectAtoms(" ( ( resid 97 or resid 190 ) and name CA ) ")
salt3 = system.selectAtoms(" ( ( resid 54 or resid 157 ) and name CA ) ")
salt4 = system.selectAtoms(" ( ( resid 54 or resid 156 ) and name CA ) ")
salt5 = system.selectAtoms(" ( ( resid 54 or resid 167 ) and name CA ) ")
salt6 = system.selectAtoms(" ( ( resid 36 or resid 158 ) and name CA ) ")
salt7 = system.selectAtoms(" ( ( resid 36 or resid 170 ) and name CA ) ")
salt8 = system.selectAtoms(" ( ( resid 57 or resid 158 ) and name CA ) ")
salt9 = system.selectAtoms(" ( ( resid 57 or resid 170 ) and name CA ) ")

dcdfile = open('../../pca/id_dcd_reduced','r').readlines()
for man in range(len(dcdfile)):
	M = dcdfile[man]
	t = M.split()
	scal_matrix = numpy.zeros((9,9))
	try:
		system.load_new_dcd("../../pca/reori_%s" % (t[-1]))
		ca1 = system.dcd.timeseries(salt1)
		ca1_ave = numpy.mean(ca1,axis=1)
		ca2 = system.dcd.timeseries(salt2)
                ca2_ave = numpy.mean(ca2,axis=1)
		ca3 = system.dcd.timeseries(salt3)
                ca3_ave = numpy.mean(ca3,axis=1)
		ca4 = system.dcd.timeseries(salt4)
                ca4_ave = numpy.mean(ca4,axis=1)
		ca5 = system.dcd.timeseries(salt5)
                ca5_ave = numpy.mean(ca5,axis=1)
		ca6 = system.dcd.timeseries(salt6)
                ca6_ave = numpy.mean(ca6,axis=1)
		ca7 = system.dcd.timeseries(salt7)
                ca7_ave = numpy.mean(ca7,axis=1)
		ca8 = system.dcd.timeseries(salt8)
                ca8_ave = numpy.mean(ca8,axis=1)
		ca9 = system.dcd.timeseries(salt9)
                ca9_ave = numpy.mean(ca9,axis=1)
		for i in range(len(ca1[0])-1):
			y = i + 1
			x1 = ((ca1[:,i][0]-ca1_ave[0])+(ca1[:,i][1]-ca1_ave[1]))/2
			x2 = ((ca2[:,i][0]-ca2_ave[0])+(ca2[:,i][1]-ca2_ave[1]))/2
			x3 = ((ca3[:,i][0]-ca3_ave[0])+(ca3[:,i][1]-ca3_ave[1]))/2
			x4 = ((ca4[:,i][0]-ca4_ave[0])+(ca4[:,i][1]-ca4_ave[1]))/2
			x5 = ((ca5[:,i][0]-ca5_ave[0])+(ca5[:,i][1]-ca5_ave[1]))/2
			x6 = ((ca6[:,i][0]-ca6_ave[0])+(ca6[:,i][1]-ca6_ave[1]))/2
			x7 = ((ca7[:,i][0]-ca7_ave[0])+(ca7[:,i][1]-ca7_ave[1]))/2
			x8 = ((ca8[:,i][0]-ca8_ave[0])+(ca8[:,i][1]-ca8_ave[1]))/2
			x9 = ((ca9[:,i][0]-ca9_ave[0])+(ca9[:,i][1]-ca9_ave[1]))/2
			scal_matrix[0][0] += numpy.dot(x1,x1)
			scal_matrix[0][1] += numpy.dot(x1,x2)
			scal_matrix[0][2] += numpy.dot(x1,x3)
                        scal_matrix[0][3] += numpy.dot(x1,x4)
			scal_matrix[0][4] += numpy.dot(x1,x5)
                        scal_matrix[0][5] += numpy.dot(x1,x6)
			scal_matrix[0][6] += numpy.dot(x1,x7)
                        scal_matrix[0][7] += numpy.dot(x1,x8)
			scal_matrix[0][8] += numpy.dot(x1,x9)
                        scal_matrix[1][0] += numpy.dot(x2,x1)
			scal_matrix[1][1] += numpy.dot(x2,x2)
                        scal_matrix[1][2] += numpy.dot(x2,x3)
                        scal_matrix[1][3] += numpy.dot(x2,x4)
                        scal_matrix[1][4] += numpy.dot(x2,x5)
                        scal_matrix[1][5] += numpy.dot(x2,x6)
                        scal_matrix[1][6] += numpy.dot(x2,x7)
                        scal_matrix[1][7] += numpy.dot(x2,x8)
                        scal_matrix[1][8] += numpy.dot(x2,x9)
                        scal_matrix[2][0] += numpy.dot(x3,x1)
			scal_matrix[2][1] += numpy.dot(x3,x2)
                        scal_matrix[2][2] += numpy.dot(x3,x3)
                        scal_matrix[2][3] += numpy.dot(x3,x4)
                        scal_matrix[2][4] += numpy.dot(x3,x5)
                        scal_matrix[2][5] += numpy.dot(x3,x6)
                        scal_matrix[2][6] += numpy.dot(x3,x7)
                        scal_matrix[2][7] += numpy.dot(x3,x8)
                        scal_matrix[2][8] += numpy.dot(x3,x9)
                        scal_matrix[3][0] += numpy.dot(x4,x1)
			scal_matrix[3][1] += numpy.dot(x4,x2)
                        scal_matrix[3][2] += numpy.dot(x4,x3)
                        scal_matrix[3][3] += numpy.dot(x4,x4)
                        scal_matrix[3][4] += numpy.dot(x4,x5)
                        scal_matrix[3][5] += numpy.dot(x4,x6)
                        scal_matrix[3][6] += numpy.dot(x4,x7)
                        scal_matrix[3][7] += numpy.dot(x4,x8)
                        scal_matrix[3][8] += numpy.dot(x4,x9)
                        scal_matrix[4][0] += numpy.dot(x5,x1)
                        scal_matrix[4][1] += numpy.dot(x5,x2)
                        scal_matrix[4][2] += numpy.dot(x5,x3)
                        scal_matrix[4][3] += numpy.dot(x5,x4)
                        scal_matrix[4][4] += numpy.dot(x5,x5)
                        scal_matrix[4][5] += numpy.dot(x5,x6)
                        scal_matrix[4][6] += numpy.dot(x5,x7)
                        scal_matrix[4][7] += numpy.dot(x5,x8)
                        scal_matrix[4][8] += numpy.dot(x5,x9)
                        scal_matrix[5][0] += numpy.dot(x6,x1)
                        scal_matrix[5][1] += numpy.dot(x6,x2)
                        scal_matrix[5][2] += numpy.dot(x6,x3)
                        scal_matrix[5][3] += numpy.dot(x6,x4)
                        scal_matrix[5][4] += numpy.dot(x6,x5)
                        scal_matrix[5][5] += numpy.dot(x6,x6)
                        scal_matrix[5][6] += numpy.dot(x6,x7)
                        scal_matrix[5][7] += numpy.dot(x6,x8)
                        scal_matrix[5][8] += numpy.dot(x6,x9)
                        scal_matrix[6][0] += numpy.dot(x7,x1)
			scal_matrix[6][1] += numpy.dot(x7,x2)
                        scal_matrix[6][2] += numpy.dot(x7,x3)
                        scal_matrix[6][3] += numpy.dot(x7,x4)
                        scal_matrix[6][4] += numpy.dot(x7,x5)
                        scal_matrix[6][5] += numpy.dot(x7,x6)
                        scal_matrix[6][6] += numpy.dot(x7,x7)
                        scal_matrix[6][7] += numpy.dot(x7,x8)
                        scal_matrix[6][8] += numpy.dot(x7,x9)
                        scal_matrix[7][0] += numpy.dot(x8,x1)
                        scal_matrix[7][1] += numpy.dot(x8,x2)
                        scal_matrix[7][2] += numpy.dot(x8,x3)
                        scal_matrix[7][3] += numpy.dot(x8,x4)
                        scal_matrix[7][4] += numpy.dot(x8,x5)
                        scal_matrix[7][5] += numpy.dot(x8,x6)
                        scal_matrix[7][6] += numpy.dot(x8,x7)
                        scal_matrix[7][7] += numpy.dot(x8,x8)
                        scal_matrix[7][8] += numpy.dot(x8,x9)
                        scal_matrix[8][0] += numpy.dot(x9,x1)
                        scal_matrix[8][1] += numpy.dot(x9,x2)
                        scal_matrix[8][2] += numpy.dot(x9,x3)
                        scal_matrix[8][3] += numpy.dot(x9,x4)
                        scal_matrix[8][4] += numpy.dot(x9,x5)
                        scal_matrix[8][5] += numpy.dot(x9,x6)
                        scal_matrix[8][6] += numpy.dot(x9,x7)
                        scal_matrix[8][7] += numpy.dot(x9,x8)
                        scal_matrix[8][8] += numpy.dot(x9,x9)
		scal_matrix /= system.dcd.numframes
		if t[-1][:1] == '9':
			scal_matrix.dump("%s_corr_ave.pickle" % (t[-1][:5]) )
		else:
			scal_matrix.dump("%s_corr_ave.pickle" % (t[-1][:6]) )
	except:
		continue	
